### ISSUE TITLE
mysql:backup produces "repository name must be lowercase

### ISSUE THREAD

**Issue by ksmandersen** [dokku/dokku-mysql#101]
Hi 👋 

I currently have an issue where calls to `dokku mysql:backup` produced the following error:

```
root@applypixels:~# dokku mysql:backup applypixels applypixels-db-backup
docker: invalid reference format: repository name must be lowercase.
See 'docker run --help'.
root@applypixels:~#
```

I've also tried to remove the `-` from the bucket name.
I am on dokku 0.12.13 and dokku-mysql 1.4.9

**Comment by josegonzalez** [comment]
Can you try:

```
dokku --trace mysql:backup applypixels applypixels-db-backup
```

And gist the output?

**Comment by ksmandersen** [comment]
I think I see the problem now. It must have to do with the PGP encryption key. What is the expected form at for that? I assumed it was the contents of an .asc file. 

Here's the output:
https://gist.github.com/ksmandersen/7609dcd6a75433cf1f928b33c5450e16

**Comment by ksmandersen** [comment]
@josegonzalez Any idea what is going wrong here?
