### ISSUE TITLE
Add a `mysql:login` command

### ISSUE THREAD

**Issue by zgulde** [dokku/dokku-mysql#113]
Would you accept a PR for a `mysql:login` command to start an interactive session with a database?

For example:

```
dokku mysql:login lolipop
```

For the purpose of running ad-hoc SQL queries in the lolipop database.

I created this command for myself as a convenience, you can see [my implementation here](https://github.com/zgulde/dokku-mysql/commit/d491ef6299550686ddfe796e916fa2e70adab4f2).

Any/all feedback welcome!

**Comment by josegonzalez** [comment]
Isn't that just `mysql:connect`?

**Comment by zgulde** [comment]
It is.

Sorry for taking your time I missed this in the documentation.
