### ISSUE TITLE
How to make user restrictions to execute some commands as connect or import.

### ISSUE THREAD

**Issue by Fran4vila** [dokku/dokku-mysql#118]
## Description of problem
How to make user restrictions to execute some commands as mysql:connect or mysql:import.

When using dokku mysql:connect servicename, it doesn't ask for any user/password, so the idea is to be able to give permissions for some commands as connect or import. In this way it could be possible to set some databases accessible and restrict some specifics.

My problem is that I want to control allow the normal users to execute dokku commands, but restrict the usage of **dokku mysql** to the sudoers.

**Comment by josegonzalez** [comment]
This isn't a feature of this plugin, nor do I think it should be. Instead, this should either be handled by something separate (such as the community dokku-acl plugin) or something in the core.
