### ISSUE TITLE
How to use plugin with remote MySQL server?

### ISSUE THREAD

**Issue by misteral** [dokku/dokku-mysql#125]
## Description of problem
I have existing MYSQL server and use it as DATABASE_URL. I what use this plugin as backup scheduler I can do this? This is right way for it? How I can do this?

**Comment by josegonzalez** [comment]
This isn't possible. Managing a third-party database is not the goal of this plugin and will never be. Please do some research on how to backup/restore your database via mysqldump, the aws cli, and cron. That's how we put together our solution for Dokku.
