### ISSUE TITLE
A way to restore service container

### ISSUE THREAD

**Issue by ypadlyak** [dokku/dokku-mysql#134]
Hi @josegonzalez 

Is there a way to restore the service container, which I've lost when switching the docker storage driver? Something like ps:rebuild for the apps.

Currently, it fails because the container is gone:
$ dokku ps:rebuild t*****g
-----> Cleaning up...
-----> Building ticketco-blog from herokuish...
-----> Checking for pre-build script in hooks
-----> Adding BUILD_ENV to build environment...
-----> Adding shared deployment-keys to build environment ...
-----> Adding host-keys to build environment ...
       Adding shared keys
Error response from daemon: could not get container for ******: No such container: ****
Error response from daemon: page not found
Error: failed to start containers: 
Error: No such container: 
2021/10/07 16:54:49 exit status 1
2021/10/07 16:54:49 exit status 1

**Comment by ypadlyak** [comment]
I see, ok

**Comment by josegonzalez** [comment]
Can you check the output of `docker ps -a` and also the output of `git -C /var/lib/dokku/plugins/enabled/mysql show`? I recently committed something that may help fix this but I wonder if you are using it/if the container exists in a weird way that is blocking it from working...

**Comment by josegonzalez** [comment]
Running `dokku mysql:start $SERVICE` _should_ start the container, but your version of the plugin is from two years ago and your version of Dokku is a bit out of date as well so I can't be sure.

**Comment by ypadlyak** [comment]
I see. Also, I have had to pull image for mysql:<version> manually for step 6, forgot to mention that
