### ISSUE TITLE
Keeping config changes between deploys

### ISSUE THREAD

**Issue by ZeCarlosCoutinho** [dokku/dokku-mysql#136]
Right now, I can create a new MySQL service with the config options that I want by adding the corresponding flags to the create command.
However, if I have to redeploy the app, it seems that I have to remember to pass the same flags as before.

Is there any way of persisting these config changes between deploys?

**Comment by josegonzalez** [comment]
When you say redeploy, what do you mean? App deploys shouldn't change any env vars related to service configs.

**Comment by josegonzalez** [comment]
Config options should be persisted to a file [here](https://github.com/dokku/dokku-mysql/blob/master/common-functions#L260-L266). Are you running the latest version of the plugin?

**Comment by ZeCarlosCoutinho** [comment]
No (v.1.9.5), but I was just inferring this from reading the docs in the Github README.

I'm not very fluent in bash/sh, so I'm not completely sure about the meaning of the lines you sent.
But I'm assuming the MySQL dokku service is already configured to read this file.

So, if I want to change the configurations after I have started the MySQL service, how can I do it? (supposedly, filesystem changes do not persist, so changing this config file should not be saved, right?)

**Comment by josegonzalez** [comment]
Please update, we handle this issue now.

We write the config outside of the docker container, and read the file when starting containers for the service. Filesystem changes _within_ the container image on unmounted paths are not persisted (which is not the case here).
