### ISSUE TITLE
Cannot upgrade mysql service

### ISSUE THREAD

**Issue by ZeCarlosCoutinho** [dokku/dokku-mysql#138]
When I try to run `dokku mysql:upgrade mysql-service`, I get a `Permission denied` on the following line:
https://github.com/dokku/dokku-mysql/blob/f31800ffa7801d7464827988cfe43ce429db991c/common-functions#L277

Running this command as `sudo` had the same results.
Why would the script not be able to `echo` to that file?

I'm running version 1.19.0 of the dokku mysql plugin.

**Comment by josegonzalez** [comment]
Please upgrade the plugin via `dokku plugin:update mysql`. This was fixed in 1.19.3.

**Comment by ZeCarlosCoutinho** [comment]
I just updated the plugin and I'm still getting the same error when I try to upgrade the MySQL service.

These are the current file permissions
```
-rw-r--r-- 1 root root 6 Jan 19 09:54  /service/root/IMAGE
```
If I run the `mysql:upgrade` command as `sudo`, I'd assume it would have permissions to change this file, but it seems that it is not enough.

Maybe I have to stop the service before I upgrade it?

**Comment by josegonzalez** [comment]
Ah I see what happened. I'll fix it on my end. One moment.

**Comment by ZeCarlosCoutinho** [comment]
Thank you very much! It's working now :smile:
