### ISSUE TITLE
Expected enviroment variables not found

### ISSUE THREAD

**Issue by scottswezey** [dokku/dokku-mysql#18]
After installing this plugin, and following the readme to create and link a database with an existing deployed app, I am unable to find the environment variables mentioned in the readme.

To test, I am using `dokku enter <app> web` and then running the `env` command. Without the environment vars, I am unsure how to configure my rails app to connect with the database.

**Comment by josegonzalez** [comment]
Did you rebuild the app? It uses docker-args to link everything in, so you'd need to either deploy or rebuild your application for the changes to take affect.

**Comment by Flink** [comment]
I cannot reproduce. When running `env`, `DATABASE_URL` is correctly set.

**Comment by materemias** [comment]
I got the same issue, i upgraded from v0.3 to 0.4 on digitalocean, and mysql and mariadb plugins don't inject env variables. what kind of info you needed ?

**Comment by josegonzalez** [comment]
What environment variables do you expect to be injected vs which aren't there?

**Comment by materemias** [comment]
the database connection parameters like $DB_NAME $DB_HOST etc...

**Comment by josegonzalez** [comment]
Those environment variables are not set, only `DATABASE_URL`. This was a conscious decision, as then we have issues like:

- Should we set it with `DB_HOST` or `DATABASE_HOST`?
- What is the suffix for passwords? `PASS` or `PASSWORD`?

If your underlying application does not understand the format of `DATABASE_URL`, every language should have some way to parse the url and provide each key as necessary. 

Hope the above information helps.

**Comment by materemias** [comment]
Unfortunately DATABASE_URL is not set either

**Comment by scottswezey** [comment]
Unfortunately, I've destroyed the testing VPS I was using and haven't yet started my production setup, so I cannot test further.

From memory, I recall that a variety of environment variables should have been set (per the readme). I did not see any of them when manually entering the container and using the linux `env` command.

```
#   DATABASE_URL=mysql://mysql:SOME_PASSWORD@172.17.0.1:3306/lolipop
#   DATABASE_NAME=/lolipop/DATABASE
#   DATABASE_PORT=tcp://172.17.0.1:3306
#   DATABASE_PORT_3306_TCP=tcp://172.17.0.1:3306
#   DATABASE_PORT_3306_TCP_PROTO=tcp
#   DATABASE_PORT_3306_TCP_PORT=3306
#   DATABASE_PORT_3306_TCP_ADDR=172.17.0.1
```

If some of these are being dropped and the readme was out of date, I won't argue with that, but as @materemias stated, not even the DATABASE_URL environment variable was visible.

**Comment by scottswezey** [comment]
@josegonzalez I do not recall if the app was rebuilt. While I am fairly sure I made several deploy attempts, there would not have been any major changes and it's possible no rebuild was triggered.

That said, I see no mention of the rebuild step being required in the readme, so I would suggest adding that where appropriate. When I begin work on my production box this weekend, I will test if that fixes the issue and create a PR with an updated readme if it does.

**Comment by josegonzalez** [comment]
Reopened this issue so we can investigate whether the DATABASE_URL is set.

**Comment by materemias** [comment]
Let me know if you need additional details

**Comment by materemias** [comment]
I could reproduce with a new app too

**Comment by josegonzalez** [comment]
@Flink I *think* what we need to do is instead of triggering a `dokku ps:restart`, we should trigger a `dokku ps:rebuild`. There can be cases where other environment variables seem to be shadowed otherwise...

**Comment by materemias** [comment]
@josegonzalez I would like to add that ps:rebuild doesn't solve my issue. some details of the environment, I used digitalocean's dokku container and updated it to 0.4 via apt-get. none of the official 0.4.0 plugins add any environment variables to the connected apps.

**Comment by Flink** [comment]
I’ve made a PR (on PG service for now) that should address those issues: https://github.com/dokku/dokku-postgres/pull/27

**Comment by josegonzalez** [comment]
@materemias when you say the environment variables aren't added, do you mean:

- via `dokku config APP`
- via `dokku run APP bash`
- via in-app checking of the environment variables

The first is expected not to work since we set the environment variable via a docker env var, not via `config:set`.

**Comment by materemias** [comment]
@josegonzalez sample app with mariadb container linked:
dokku config
=====> myapp config vars
DOKKU_NGINX_PORT: 80

dokku run printenv
HOSTNAME=c0eec435f3xx
CURL_CONNECT_TIMEOUT=5
TERM=xterm
CACHE_PATH=/cache
HEROKUISH_VERSION=0.3.3
DOKKU_NGINX_PORT=80
PATH=/app/.heroku/php/bin:/app/.heroku/php/sbin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
SELF=/exec
PWD=/app
SELF_EXECUTABLE=/bin/herokuish
PS1=${debian_chroot:+($debian_chroot)}\u@\h:\w\$
SHLVL=1
HOME=/app
CURL_TIMEOUT=30
BASH_FUNC_composer%%=() {  php composer.phar "$@"
}
_=/usr/bin/printenv

in app checking also fails.
hard linking the connection parameters works.

**Comment by josegonzalez** [comment]
Very odd indeed. @Flink has an open PR against the postgres plugin which *should* fix these issues, and we'll port everywhere once that goes through.

**Comment by josegonzalez** [comment]
Note: I've tested this against both a rails app and a php application, in both a new dokku install as well as an upgrade.

**Comment by materemias** [comment]
@josegonzalez same finding? please ping me once the postgres fix goes upstream and i can check if it solves the issue

**Comment by josegonzalez** [comment]
The link/unlink changes have happened, can you try the following and see if it works as desired now?

```shell
dokku mysql:unlink SERVICE APP
dokku mysql:link SERVICE APP
```

**Comment by materemias** [comment]
I have tested the mariadb plugin and it worked after the update

**Comment by josegonzalez** [comment]
Thanks for checking!
