### ISSUE TITLE
MySQL container is hit or miss on creation

### ISSUE THREAD

**Issue by DavidCorrado** [dokku/dokku-mysql#37]
I know your documentation says you support 1.8 but it appears the postgres dokku plugin works but the mysql one does not for some reason.  A popular webhost DigitalOcean defaults to 1.9 so maybe the plugin should support it now.  On digital ocean I create the default dokku application which is Unbuntu 14.04.   Dokku 0.4.4, Docker 1.9.0.
It never gets past where it says waiting on the container
`root@Events:~# dokku mysql:create events`
`-----> Starting container`
`       Waiting for container to be ready`

I found that sometimes it creates the container correctly but most of the time it does not.  This command must not be creating the container all of time it seems
docker run --name dokku.mysql.events28 -v /var/lib/dokku/services/mysql/events28/data:/var/lib/mysql -e MYSQL_ROOT_PASSWORD=AAA -e MYSQL_USER=mysql -e MYSQL_PASSWORD=AAA -e MYSQL_DATABASE=events28 --env-file=/var/lib/dokku/services/mysql/events28/ENV -d --restart always --label dokku=service --label dokku.service=mysql mysql:5.6.26

**Comment by DavidCorrado** [comment]
I will consider this closed as I dont think this is an issue with your plugin

**Comment by DavidCorrado** [comment]
Just to note in here if someone else has this problem is it seems you need 1 GB ram for it to create the container properly.  It seemed like it tried to create it but the container kept restarting.

https://github.com/docker-library/docs/issues/278

You may want to put this in maybe a FAQ.  At minimum someone might read this and save them all the time I wasted =)

**Comment by josegonzalez** [comment]
Dokku itself says the minimum memory for running properly is 1GB. I suppose we can just duplicate that for those in a hurry who didn't read that ;)

**Comment by DavidCorrado** [comment]
Yeah definitely didn't read that. =).  I will also maybe push a recommendation to Digital ocean to maybe give you a warning to not create a dokku image with less than 1GB ram.
