### ISSUE TITLE
mysql:import failed

### ISSUE THREAD

**Issue by qqiangwu** [dokku/dokku-mysql#39]
I've created a new mysql service and want to init it with mysql scripts. But when I run the following:
```
dokku mysql:import xxxx < create.sql
```

The content of create.sql is:
```
DROP DATABASE IF EXISTS `swenet`;
CREATE DATABASE `swenet`;
ALTER SCHEMA `swenet` DEFAULT CHARACTER SET utf8;

USE swenet;
```

I got `ERROR 1044 (42000) at line 1: Access denied for user 'mysql'@'%' to database`

**Comment by qqiangwu** [comment]
I'm sorry, I just misused the plugin.

**Comment by josegonzalez** [comment]
What was the underlying issue?

**Comment by qqiangwu** [comment]
I `mysql:create lalalaa`, and just want to run the following script after connection:
```
DROP DATABASE IF EXISTS `swenet`;
CREATE DATABASE `swenet`;
ALTER SCHEMA `swenet` DEFAULT CHARACTER SET utf8;

CREATE TABLE 'abc' (....)
```

It was rejected. The issue is that when I `mysql:create lalala`, I have a database already, so all I have to do is just to create my tables directly, so I run:
```
CREATE TABLE 'abc' (....)
```

And it was all right!

**Comment by josegonzalez** [comment]
Gotcha, makes sense to me :)
