### ISSUE TITLE
On connection attempt I get error: unknown mysql server host 'dokku-mysql-appname'

### ISSUE THREAD

**Issue by kbhardwaj** [dokku/dokku-mysql#42]
I have my database_url:
DATABASE_URL=mysql://mysql:SOME_PASSWORD@dokku-mysql-sagemob:3306/sagemob

But when I try to connect to mysql I get an unknown host error:
ERROR 2005 (HY000): Unknown MySQL server host 'dokku-mysql-sagemob' (0)

How can I fix this?

**Comment by josegonzalez** [comment]
Where are you trying to connect from?

**Comment by kbhardwaj** [comment]
I'm ssh'd into my digitalocean droplet. I'm trying to connect from the command line there using: 
mysql -u mysql -h dokku-mysql-sagemob -p
 
From the database_url I'm assuming my user is 'mysql', although I've tried root and admin as well.

**Comment by kbhardwaj** [comment]
Ah, I didn't initally notice this command:
dokku mysql:connect appname

With the old mysql plugin I was connecting to mysql server like I mentioned above. I'll close this, but just for my information, how can I connect using the mysql -u -h -p command?

**Comment by josegonzalez** [comment]
You'll need to use the `mysql:expose` command to connect remotely. We're secure by default, so don't expose ports to the outside world. The host will then just be the host of your server.
