### ISSUE TITLE
is it possible to link multiple apps to single mysql container with separate database per app?

### ISSUE THREAD

**Issue by kminek** [dokku/dokku-mysql#44]
i would love to see an example code in the documentation

**Comment by josegonzalez** [comment]
This functionality is being tracked in #35, and is not possible at this time. Please see that issue for more information.

**Comment by josegonzalez** [comment]
See dokku/dokku-redis/issues/64 for more information.

**Comment by spnkr** [comment]
why not just open up the mysql console and make a new db for your app

```
> mysql -u[get this from your dokku mysql config] -p -h[get this from your dokku mysql config]
Enter password: > [get this from your dokku mysql config] ;

> create database mynewdatabase;
# then make users for this db, store the unames/passwords as ENV vars or whatever
> exit;
```

**Comment by spnkr** [comment]
Note I started using dokku-mysql literally 1h ago so I don't know if the above solution is a good one

**Comment by josegonzalez** [comment]
That works fine, but the `DATABASE_URL` will be wrong.

For further discussion, please see the linked issue.
