### ISSUE TITLE
Connecting to MySQL in Sails.js app

### ISSUE THREAD

**Issue by dgroch** [dokku/dokku-mysql#45]
Hi,

I'm having trouble trying to connect to MySQL in my Sails.js app.

The error I keep getting when I try to create a record is 

```
{
  "error": "E_UNKNOWN",
  "status": 500,
  "summary": "Encountered an unexpected error",
  "raw": {}
}
```

I've set adapter config in `/config/connections.js`

```
mysql: {
    adapter: 'sails-mysql',
    host: 'dokku-mysql-webscraper',
    port: 3306,
    user: 'mysql',
    password: 'xxxx',
    database: 'xxxx'
  },
```

and specified the adapter as the default for all models, ie. in `/config/development.js`
```
models: {
    connection: 'mysql'
}
```

When I ssh into the box, I can access the mysql service find with `dokku mysql:connect webscraper`

I've tried to inspect the tables with `show tables` but mysql then just returns a blank prompt. Same if i try `show databases`.

Any ideas?!
I'm all out

**Comment by dgroch** [comment]
OK, so I think i might have this sorted!
First-time run of the app needed to be in development mode to create the database tables.

Here's the relevant Part of the docs

```
If you are using a relational database such as MySQL, there is an additional step. Remember how Sails sets all your models to migrate:safe when run in production? That means no auto-migrations are run when lifting the app...which means by default your tables won't exist. A common approach to deal with this during the first-time setup of a relational database for your Sails app goes as follows:

Create the database on the production database server (e.g. frenchfryparty)

Configure your app locally to use this production database, but don't set the environment to 'production', and leave your models' configuration set to migrate: 'alter'. Now run sails lift once-- and when the local server finishes lifting, kill it.

Be careful! You should only do this when there is no data in the production database.
If this makes you nervous or if you can't connect to the production database remotely, you can skip the steps above. Instead, simply dump your local schema and import it into the production database.
```

I lost hours on this one!

**Comment by josegonzalez** [comment]
It would be great if you could make a pull request against our documentation - in the docs repo - in regards to this issue. Would help the next person *not* lose hours on this one :)

**Comment by josegonzalez** [comment]
Thinking this through further, there is no reason to believe that dokku should make any claim as to what is in your database. It is wholly up to the developer to apply any database migrations, and noting down how each and every web framework deals with this problem is wayyyy outside the scope of what dokku does.
