### ISSUE TITLE
Can we have plugn trigger at for at least all official plugins?

### ISSUE THREAD

**Issue by pltchuong** [dokku/dokku-mysql#54]
That would be great if we have triggers at plugins level so we can hook into it

**Comment by josegonzalez** [comment]
What would this plugin trigger do? Where would it be located? What is its name?

**Comment by pltchuong** [comment]
since plugin can be flexible enough for everybody, so I guess one kind of trigger would be enough with parameters, so something like this `plugn trigger plugin-command "$APP" "$SERVICE_NAME" "$COMMAND" "$PARAMS"`

The point of this is to collect information when a plugin command is executed. For instance we have to run a `find` to get all plugins that linked to an app

**Comment by josegonzalez** [comment]
- What is `$COMMAND` in this case?
- What happens for `mysql:list`, which isn't attached to a service? 
- Many of the commands do not reference an `$APP`, so adding that seems wrong here.

**Comment by josegonzalez** [comment]
This issue was moved to dokku/dokku-redis#84
