### ISSUE TITLE
Character set

### ISSUE THREAD

**Issue by srna** [dokku/dokku-mysql#61]
It would be nice to be able to specify character set and collation. Even better would be to being able to specify it as a global default for server and separately by instance. Or at least use utf8 & utf8_general_ci as hard-wired default, as most of the apps use it.

**Comment by aminotsukasa** [comment]
Hi srna
I have a same problem for japanese user.
I create a branch with mysqld additional_mysqld_config function.

this is a usage sample code changing mysqld character_set_server.

```
$ export ADDITIONAL_MYSQLD_CONF="[mysqld]\ncharacter-set-server=utf8\ncollation-server=utf8_general_ci
$ dokku mysql:create japanese-test
$ cat  /var/lib/dokku/services/mysql/japanese-test/config/additional_mysqld_config.cnf
[mysqld]
character-set-server=utf8
collation-server=utf8_general_ci

$ dokku mysql:enter ja-test3 mysql -u mysql -p ja-test3 -e "SHOW VARIABLES LIKE  'char%';"
+--------------------------+----------------------------+
| Variable_name            | Value                      |
+--------------------------+----------------------------+
| character_set_client     | latin1                     |
| character_set_connection | latin1                     |
| character_set_database   | utf8                       |
| character_set_filesystem | binary                     |
| character_set_results    | latin1                     |
| character_set_server     | utf8                       |
| character_set_system     | utf8                       |
| character_sets_dir       | /usr/share/mysql/charsets/ |
+--------------------------+----------------------------+

source code is here .
https://github.com/aminotsukasa/dokku-mysql/tree/option_mysql_conf

josegonzalez 
Can I send pull request with this branch?

**Comment by srna** [comment]
Hi aminotsukasa

Thank you so much for this patch. I myself made a patch inspired by your, having just utf8 as the charset. I made also a pull request, but it is not likely that they accept it. Serves me well, though.

My repo is https://github.com/srna/dokku-mysql

Thanks.
Tomas

**Comment by josegonzalez** [comment]
#62 is up, and closes this. I have a clarifying question, otherwise it'll def be merged in. It is a pretty sane default imo.
