### ISSUE TITLE
Plugin.toml issue

### ISSUE THREAD

**Issue by chiedo** [dokku/dokku-mysql#63]
Hi guys,

I'm running Dokku 0.4.0 and installed dokku-mysql.

Things are working but I keep seeing this error.
open /var/lib/dokku/plugins/available/mysql-plugin/plugin.toml: no such file or directory

Any ideas?

Thanks

**Comment by chiedo** [comment]
I see... that was left over from the other mysql plugin I tried.

Sorry!

**Comment by josegonzalez** [comment]
@chiedo I'd also recommend upgrading Dokku when you have a chance (or maybe try it on a new server), we've advanced quite a bit and the functionality is much nicer now.

**Comment by chiedo** [comment]
Oops @josegonzalez, I actually am on 0.7.2 Haha.

Thanks,
