### ISSUE TITLE
Access denied for user 'mysql' when connecting from app

### ISSUE THREAD

**Issue by nikhil-bhandari** [dokku/dokku-mysql#72]
Hi,

I'm new to dokku and I'm trying to setup my first app but I keep on getting this error when setting up mysql.

```
2017-03-07T18:31:02.601454732Z app[web.1]: Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Access denied for user 'mysql'@'%' to database 're_data:3306'
```

`dokku mysql:connect re_data` this command works, but my app keeps on throwing the error. The code base is already running on heroku and when I switch the url to Amazon RDS app starts working.

On mysql I can see that host has a "wildcard" (%)

```
mysql> SHOW GRANTS FOR 'mysql'@'%';
+-------------------------------------------------------+
| Grants for mysql@%                                    |
+-------------------------------------------------------+
| GRANT USAGE ON *.* TO 'mysql'@'%'                     |
| GRANT ALL PRIVILEGES ON `re_data`.* TO 'mysql'@'%' |
+-------------------------------------------------------+
2 rows in set (0.00 sec)
```

I looked through other issues on github but still couldn't find anything that solves this error.

Am I'm missing something? I used following steps to setup the database.

```
dokku mysql:create re_data
dokku mysql:link re_data re-app
dokku config:set re-app  CLEARDB_DATABASE_URL='mysql://mysql:pass@dokku-mysql-re-data:3306/re_data?reconnect=true'
dokku mysql:import re_data < data-dump-2017-03-07.sql
```

**Comment by josegonzalez** [comment]
Does your database dump accidentally overwrite the mysql user?

**Comment by josegonzalez** [comment]
What happens when you run `dokku mysql:connect re_data`? Can you connect/query your database?

**Comment by nikhil-bhandari** [comment]
Yes that works fine!

**Comment by josegonzalez** [comment]
So are you sure the `CLEAR_DATABASE_URL` is set correctly?

**Comment by nikhil-bhandari** [comment]
Yes, CLEAR_DATABASE_URL matches DATABASE_URL set by dokku-mysql

```
CLEARDB_DATABASE_URL:            mysql://mysql:480ba76c3fa51075@dokku-mysql-re-data:3306/re_data
DATABASE_URL:                    mysql://mysql:480ba76c3fa51075@dokku-mysql-re-data:3306/re_data
```

*Intentionally including password.

**Comment by josegonzalez** [comment]
iirc we use that same username/pass for `mysql:connect`, so this sounds like its not related to dokku.

What happens if you `mysql:expose` the service and try to connect to it using a gui client?

**Comment by nikhil-bhandari** [comment]
I think it was something related to the framework that we were using. 

I removed the port number and it started working.

Thanks for helping!
