### ISSUE TITLE
mysql:backup-schedule asks for sudo password

### ISSUE THREAD

**Issue by mopx** [dokku/dokku-mysql#73]
I saw a similar issue on the postgres plugin, I tried reinstalling the plugin like they suggested, it didn't worked.

any ideas? thanks.

**Comment by perminder-klair** [comment]
+1 Same issue, any solution?

**Comment by OKNoah** [comment]
Mine asks for user password, then "dokku" password.

**Comment by josegonzalez** [comment]
Should be fixed now.
