### ISSUE TITLE
Disable import on production container

### ISSUE THREAD

**Issue by yourivdlans** [dokku/dokku-mysql#75]
Would there be a possibility to disable certain commands on certain containers? I would use this to disable importing into the production container.

Or would there already be a way to disable this?

**Comment by josegonzalez** [comment]
There is no way to disable commands on specific containers. You can use the `user-auth` plugin trigger to simulate this if you wish. Documentation for that is [here](http://dokku.viewdocs.io/dokku/development/plugin-triggers/#user-auth).
