### ISSUE TITLE
How to access as root or admin user?

### ISSUE THREAD

**Issue by hugoruscitti** [dokku/dokku-mysql#76]
Hi, i are using a separate application with phpmyadmin to access to the database by
using the same string connection. But i don't have admin rights by using the "mysql" named
user.

There is any way to get the root user to the mysql database instance?

**Comment by josegonzalez** [comment]
I believe it is output via `dokku mysq:info SERVICE`.

**Comment by hugoruscitti** [comment]
nop, sadly it only show normal credentials, no root access to database settings :(

How i can get admin access to the database?

**Comment by josegonzalez** [comment]
The root password is stored in a file called `ROOTPASSWORD` in the `service-root` dir.

**Comment by hugoruscitti** [comment]
Thank you very much, your suggestion has worked perfectly !!

**Comment by barmmie** [comment]
@hugoruscitti 
I'm having the same issue
I'm sorry if the answer to this is obvious but how do i access the service-root directory?

Regard
