### ISSUE TITLE
How do I upload my .sql file so I can import it?

### ISSUE THREAD

**Issue by wootwoot1234** [dokku/dokku-mysql#83]
I did a search and didn't' find any examples of how to migrate from another mysql database on a different server.  

How do I get my upload my .sql file and reference it with the import command?

Thansk!

**Comment by josegonzalez** [comment]
I don't know how you upload files to your server - sftp or scp should work.

As far as using the import command, try the following:

```
dokku mysql:help import
```

**Comment by wootwoot1234** [comment]
I'll check it out.

Will it only import dump files or will it accept .sql?

**Comment by wootwoot1234** [comment]
For others that come across this same issue.  I found [this]:(https://stackoverflow.com/questions/44306876/how-to-import-mysql-database-using-dokku)

    dokku mysql:create db_name
    dokku mysql:link db_name app_name

    sftp root@ipmydroplet
    put localdirectory/filename

    dokku mysql:import db_name < filename

**Comment by josegonzalez** [comment]
It just calls the `mysql` bin in the container and pipes the file into it.
