### ISSUE TITLE
Connection refused with Python and Peewee

### ISSUE THREAD

**Issue by rogercorrea** [dokku/dokku-mysql#85]
Please,

My MySQL database work and I can access externally but my Python app (with Peewee ORM) don't work. For me his return a error "Connection refused" but I did set the parameter of the DATABASE_URL with the address generated by Dokku.

I executed dokku mysql:link and doens't worked.
What can cause the error?

> peewee.OperationalError: (2003, "Can't connect to MySQL server on 'localhost' ([Errno 111] Connection refused)")

Thanks!

**Comment by josegonzalez** [comment]
How did you set `DATABASE_URL`?

**Comment by josegonzalez** [comment]
Closing as there hasn't been any followup.
