### ISSUE TITLE
Feature Request: Google Cloud Backup Support

### ISSUE THREAD

**Issue by colinschoen** [dokku/dokku-mysql#87]
The newly added S3-Backed Amazon backups is great. It would be helpful to also support Google Cloud Storage.

**Comment by josegonzalez** [comment]
That would be cool, but I don't have time to add support for Google Cloud Storage.

Would you be willing to do either of the following?

- sponsor the development of the functionality
- make a pull request with the associated changes

**Comment by colinschoen** [comment]
We currently need this feature ASAP so I am in the process of writing a python package that will work for now. When I have some time I will work on a PR for this.

**Comment by colinschoen** [comment]
For now will be using:

https://github.com/colinschoen/dokku-mysql-backup
