### ISSUE TITLE
Unable to import mysqldmp  ( permissions issue)

### ISSUE THREAD

**Issue by dpanyam** [dokku/dokku-mysql#88]
I have created a myql service and linked it to my app. I have a MYSQLDUMP file from where i would like to import. The default user "mysql" created as part of setting up the mysql service has no permissions although it is the root user.

I chatted with Savant and he asked me to file this issue. Appreciate if this can be fixed ASAP because we are ready to move to production

root@ip-172-31-0-23:/home/ubuntu# dokku mysql:import main < dump.sql
**ERROR 1227 (42000) at line 958: Access denied; you need (at least one of) the SUPER privilege(s) for this operation**
root@ip-172-31-0-23:/home/ubuntu#

**Comment by dpanyam** [comment]
Import failing with the default mysql user created while setting up the mysql service need to use root user and ROOTPASSWORD submitted a PR

**Comment by josegonzalez** [comment]
Closing as there is a pull request open.
