### ISSUE TITLE
Can't remote connect to Mysql and MongoDB services in DOKKU

### ISSUE THREAD

**Issue by toitoine31** [dokku/dokku-mysql#90]
Hi,

I have dokku installed on my machine with multi apps running and some services : MongoDB and MySQL.

I used : 

`dokku mongo:expose my_database`
`dokku mysql:expose my_database`

But i cant connect with Datagrip or Robomongo tools with remote connection.

I also used the information given by :

`dokku mongo:info my_database`
`dokku mysql:info my_database`

Same with the terminal to access MySQL :

`mysql -u mysql -h dokku-mysql-upload --port <exposed_port> -p`

I realy don't understand where is the problem.

Thank's,
Antoine

**Comment by josegonzalez** [comment]
The hostname is an internal docker hostname. You'll need to use your server's ip address or hostname when connecting remotely.

Hope that helps.
