### ISSUE TITLE
Cron jobs don't schedule if service name contains dot character

### ISSUE THREAD

**Issue by ilyapoz** [dokku/dokku-mysql#93]
https://github.com/dokku/dokku-mysql/blob/c6f38b2c1b4567d3999023f254b085ea0e61fa8b/common-functions#L190

Files in /etc/cron.d can only contain alphanumeric characters, hyphen and underscore for popular cron implementations, otherwise the jobs are silently ignored.

We should probably change the way dokku-mysql generates filenames. Ideas?

**Comment by josegonzalez** [comment]
Don't name your service with a dot.
