### ISSUE TITLE
Custom config not being loaded - MySQL 5.7.4

### ISSUE THREAD

**Issue by devkokov** [dokku/dokku-mysql#96]
Cannot load custom config variables in MySQL 5.7.4.

Steps to reproduce:

```
export MYSQL_IMAGE_VERSION="5.7.4"
dokku mysql:create test_db
dokku mysql:connect test_db
SHOW VARIABLES LIKE 'PERFORMANCE_SCHEMA';
```

This should output "performance_schema OFF", because by default, we have this file `/var/lib/dokku/services/mysql/test_db/config/disable_performance_schema.cnf` containing:
```
[mysqld]
performance_schema = 0
```

Any ideas?

This is not an issue with MySQL 5.5.57 for example, but unfortunately I have to use 5.7.4 specifically!

Dokku version 0.10.5

**Comment by devkokov** [comment]
Here's my temporary workaround, for anyone with the same problem:

```
dokku mysql:enter DB_NAME
printf "[mysqld]\nperformance_schema = 0\n" > /etc/mysql/my.cnf
exit
dokku mysql:restart DB_NAME
dokku ps:restart APP_NAME
```

**Comment by josegonzalez** [comment]
Seems like maybe the 5.7.4 image doesn't load the data from the same directory?
